FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY . .
RUN mvn -q -DskipTests package -pl usuario-service -am

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/usuario-service/target/usuario-service-1.0.0.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
